### ISSUE TITLE
Question: How to get it to work in a Nuxt 3 app?

### ISSUE THREAD

**Issue by chanon** [sxzz/vue-functional-ref#1]
Sorry for asking, but I've tried everything I can think of, and I can't get it to work in my Nuxt 3 app. 

I added the plugin to the `nuxt.config.ts` and the path to `tsconfig.json`

The Playground is working correctly in my VS Code with Volar, but in my Nuxt 3 project it says `"This expression is not callable"` whenever I try to call a ref to get its value.

**Comment by sxzz** [comment]
Demo: https://github.com/sxzz/nuxt-functional-ref

It doesn't support SSR/SSG at the moment.

**Comment by chanon** [comment]
Thank you!!

**Comment by sxzz** [comment]
If you're using pnpm, try `pnpm.overrides`. It works perfectly!
https://github.com/sxzz/nuxt-functional-ref/commit/01cd6d84ad1994d7a0e0eb335b08b1aa99f970f7
